---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backend-apps
spec:
  owner: backend-apps-team
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api
spec:
  type: graphql
  lifecycle: experimental
  owner: backend-apps-team
  system: backend-apps
  definition:
    $text: https://github.com/backstage-cg/backend-apps/blob/main/gateway-api-schema.json
  providesApis: [booking-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: booking-api
spec:
  type: graphql
  lifecycle: experimental
  owner: backend-apps-team
  system: backend-apps
  definition: http
  subComponentOf: [gateway-api]
