---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backend-apps
spec:
  owner: backstage-cg
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-api
spec:
  type: graphql
  lifecycle: experimental
  owner: backstage-cg
  system: backend-apps
  providesApis: [booking-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: booking-api
spec:
  type: graphql
  lifecycle: experimental
  owner: backstage-cg
  system: backend-apps
  definition: graphql
  subComponentOf: [gateway-api]
