---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backend
spec:
  owner: backend-apps-team
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backend-apps
spec:
  type: url
  targets:
    - https://github.com/backstage-cg/backend-apps/blob/main/apis/booking-api/catalog-info.yaml
    - https://github.com/backstage-cg/backend-apps/blob/main/apis/consumer-api/catalog-info.yaml
    - https://github.com/backstage-cg/backend-apps/blob/main/apis/gateway-api/catalog-info.yaml
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend-apps
  description: Backend Applications serving multiple GraphQL APIs.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - internal
    - monorepo
spec:
  type: service
  lifecycle: production
  owner: backend-apps-team
  system: backend
  providesApis:
    - gateway-api
    - consumer-api
    - booking-api

