---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: booking-api
  description: GraphQL API for booking.
  links:
    - url: http://localhost:3000/apollo-explorer
      title: Apollo Explorer
      icon: code
  tags:
    - javascript
    - graphql
    - backend
    - booking
    - api
    - nodejs
    - express
  annotations:
    backstage.io/techdocs-ref: dir:./apis/booking-api # This is a relative path to the techdocs directory
spec:
  type: graphql
  lifecycle: experimental
  owner: backend-apps-team
  system: backend
  definition:
    $text: https://github.com/backstage-cg/backend-apps/blob/main/booking-api-schema
  subComponentOf: [gateway-api]